name: '🐛 Report a Bug'
description: Report a bug affecting SA:GL
title: "[Bug]"
labels: 
 - bug-report
assignees:
 - tmfksoft

body:
  - type: dropdown
    id: affected-area
    attributes:
      label: What area(s) of SA:GL does it impact?
      options:
        - SA:MP Integration
        - Cloud Integration
        - Game Saves
        - Gallery
        - Statistics
        - Other / New
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Explain the issue you're seeing
    validations:
      required: true

  - type: input
    id: sagl-version
    attributes:
      label: SA:GL Version
    validations:
      required: true

  - type: dropdown
    id: os-version
    attributes:
      label: What operating system are you experiencing the issue on?
      options:
        - Windows 10
        - Windows 7
        - Linux (Ubuntu)
        - Linux (Other - tell us what!)
        - Windows 11
        - Other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Steps on how to reproduce the issue you're seeing
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
